name: dio
description: A powerful Http client for Dart, which supports Interceptors, FormData, Request Cancellation, File Downloading, Timeout etc.
version: 1.0.13
homepage: https://github.com/flutterchina/dio
author: wendux <824783146@qq.com>

environment:
  sdk: '>=1.9.0 <3.0.0'

dependencies:
  cookie_jar: ^0.0.7

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.0

