
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/vocdoni/go-dvote-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Dvotemobile_FRAMEWORK_H__
#define __Dvotemobile_FRAMEWORK_H__

#include "Dvotemobile.objc.h"
#include "Universe.objc.h"

#endif
